# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 08 Aug 2020 17:14:04 +0000
*               @ALL          0
*               @user         8
