# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 08 Aug 2020 17:14:04 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

sgdlta:$2y$10$zeLkZyXzmZZnroT4byM5cuYlhsbAo3tKGxYCCYYhk4imt0Hhf8tY.:CY:sigdelta34@yahoo.com:admin,user
